export default {
  BazQux: 'BazQux',
  FooBar: 'FooBar',
  Atia: 'Atia',
  Desmond: 'Desmond',
  Eowin: 'Eowin',
  Fearn: 'Fearn',
  Fennix: 'Fennix',
  Jeremy: 'Jeremy',
  Kleorg: 'Kleorg',
  Lahin: 'Lahin',
  Makalani: 'Makalani',
  Mazzy: 'Mazzy',
  Mesekiu: 'Mesekiu',
  Olivia: 'Olivia',
  One: 'One',
  Prizilla: 'Prizilla',
  Puddlemouth: 'Puddlemouth',
  ShenYuan: 'ShenYuan',
  Simon: 'Simon',
  Ty: 'Ty',
  Widget: 'Widget',
  Yukeko: 'Yukeko',
  Zelkie: 'Zelkie'
}